### ISSUE TITLE
How to set mode = 'tokens'?

### ISSUE THREAD

**Issue by runvnc** [gptlabs/openai-streams#10]
Hello, for the Chat one, I seem to be getting a Uint8Array instead of delta objects as shown in the documentation. Do I just add `mode: 'tokens' as an option? Its not shown in the README.

**Comment by ctjlewis** [comment]
My apologies, yeah all the streams emit Uint8Array chunks, you have to parse them yourself still.

I'm hoping to upgrade this all soon so that the streams go away completely, and you just get a buffer generator with chunk type `string[]`. 

`

**Comment by PanMan** [comment]
This still doesn't explain how to set the mode...

**Comment by ctjlewis** [comment]
@PanMan I updated the docs for you guys. Streaming options for the library are set in the third parameter, the first two are OpenAI-specific:

```
await OpenAI(
    "chat",
    { messages: [/* ... */] },
    { mode: "raw" }
   )
```

**Comment by PanMan** [comment]
Thanks @ctjlewis - that explains, I was looking in the first object
