### ISSUE TITLE
"max_tokens" not working for chat completion

### ISSUE THREAD

**Issue by someguy9** [gptlabs/openai-streams#16]
I believe "max_tokens" is missing for CreateChatCompletionRequest in https://github.com/gptlabs/openai-streams/blob/0892cb4e86419b55463d5fb36dbd002ce0e32832/src/lib/pinned.ts#L25

I get an error that doesn't allow me to set max_tokens when using a chat competition (great work on this library by the way!)

**Comment by someguy9** [comment]
Well you are amazing. thank you.

**Comment by ctjlewis** [comment]
This was not supported in OpenAI's original release, and so the types were a little behind. This was updated.

Ping: https://github.com/transmissions11/flux/issues/12#issuecomment-1496909243

**Comment by ctjlewis** [comment]
No worries! Working with the Chat streams is still kind of crazy, we need to merge the hacks we've used in practice into the library soon. Until then, you'll probably find it a pain to use in production, where chunks may contain several objects or parts of objects.
