### ISSUE TITLE
openai-streams/node not working on Vercel

### ISSUE THREAD

**Issue by someguy9** [gptlabs/openai-streams#18]
Is anyone else having this issue?

I'm using openai-streams/node and in my local environment the response works correctly (streaming piece by piece) but when I push to Vercel the response sends then entire stream back at once (rather than chunks), very odd.

**Comment by ctjlewis** [comment]
Are you on latest? See https://nextjs-openai.vercel.app, which uses latest.

**Comment by someguy9** [comment]
Yes using v5 that was just released, is that vercel example using the edge function? I am specifically using the openai-streams/node version without using edge runtime.

**Comment by ctjlewis** [comment]
Oh, right - that was not updated... I wonder if Vercel made some kind of change to how `Readable` works...

**Comment by someguy9** [comment]
I really appreciate it, this script makes it so easy to make a stream. Let me know if I can do anything to help. It is frustrating since with the /node package it makes it SO easy to just drop in and use :), works super well in my local environment.

**Comment by ctjlewis** [comment]
I know, it also usually solves this problem of the production Vercel buffer... I'll have to reach out to them, this was working until just recently right?

Can you downgrade back to the last version that worked for you? If it's broken again in production, I'll know it's their pipeline and not the library and can get in touch with them.

**Comment by ctjlewis** [comment]
I did repro at https://nextjs-openai.vercel.app/node. If you can just check whether downgrading to the last version that worked for you resolves it, I'll know if it's our problem or Vercel's.

**Comment by someguy9** [comment]
I'll test more but I never had it working on Vercel, I was only testing on local initially. (I also updated to next 13.3 and it didn't seem to do anything)

**Comment by someguy9** [comment]
Let me know if you need me to contact Vercel also, it sounds like you'll see what's going on though.

**Comment by ctjlewis** [comment]
Yeah, go ahead and bug them, I've asked them for help with this no less than three times and they've refused to make themselves available. I'm basically stuck trying to reverse-engineer what's wrong with production streams on regular API routes. 

`Readable.from(AsyncGenerator)` yields out that one chunk as we're seeing, and `for await ... of generator { res.write(...) }` or `res.send(iterator or stream)` simply sends no data. As you noted, the divergence between local dev and production is hard to bug.

Presumably in App Dir this would not happen, and you could probably return the regular `Response()` object. I'd use edge runtime if possible.

cc @leerob @steven-tey

**Comment by ctjlewis** [comment]
`Readable.from(Iterable).pipe(res)` also does not work, still loads as one chunk.

Basically, it does not appear that Next supports streams in legacy API Routes. I did not know this at the time of writing this library and also just saw it work locally and figured it was okay. Sorry for you to find out this way. 😔

**Comment by someguy9** [comment]
Thank you @ctjlewis, just opened a thread with them. Would a workaround be to not use Next? or would be focusing on supporting edge runtime be the key.

**Comment by ctjlewis** [comment]
I would absolutely stick with Next and use Edge runtime. 

If you tell me more about why you're on Node runtime I can maybe help you workaround whatever is blocking you from using Edge.

**Comment by someguy9** [comment]
Basically I have a .to file that builds prompts and sends them to open ai, the thing is I record results in Supabase, grab external content via another package to add to the prompt. Basically a bunch of small packages added to my core open ai file that I use to render. I'm guessing I can make a mix of files and use edge just going to be a lot of work.

**Comment by someguy9** [comment]
@ctjlewis I reworked my file to use the app folder but the only issue now is I don't know the correct way to "return" I get this "TypeError: dest.on is not a function" error but I think I am just not calling the stream correctly.

**Comment by someguy9** [comment]
Nevermind "return new Response(streamResponse as any)" seems to work, going to test on Vercel now :)

**Comment by someguy9** [comment]
It worked but for people reading this in the future, it doesn't seem to get around the Vercel 60s limit, guessing using the "edge" runtime is the only way to do it.
