### ISSUE TITLE
Abort streams

### ISSUE THREAD

**Issue by Amareis** [gptlabs/openai-streams#20]
I want to abort requests in some cases (e.g. when user closed dialog). Currently `stream.cancel()` doing nothing.

**Comment by ctjlewis** [comment]
Sorry, yeah, the `ReadableStream` is locked by the time you get it. You can pass a `{ controller }` option now, and call `controller.abort()` to stop the stream.

For now you'll need to manually catch the `AbortError`.

**Comment by Amareis** [comment]
God speed! Thank you, it's working now.
