### ISSUE TITLE
Function TokenParser

### ISSUE THREAD

**Issue by rossanodr** [gptlabs/openai-streams#21]
how the Function TokenParser should be used Consuming streams in Next.js Edge functions?
can you give an example?
thanks

**Comment by rossanodr** [comment]
I am asking, because after the vercel deployment some text are returning as '��'.

**Comment by ctjlewis** [comment]
Can you send a repro? The demo for [`nextjs-openai`](https://github.com/gptlabs/nextjs-openai) uses this library in production.

**Comment by ctjlewis** [comment]
I'll reopen if you send a repro, ty.

**Comment by TimPchelintsev** [comment]
I have same bug when using cyrillic symbols...
