### ISSUE TITLE
use of custom env var name

### ISSUE THREAD

**Issue by Johnrobmiller** [gptlabs/openai-streams#3]
the env var name OPENAI_API_KEY is not the api key used for our project, and so adding this in and duplicating the openai key just for this one library is very silly. 

In my opinion, automatically snagging anything from the user's env increases complexity by transferring the complexity from the code itself directly into the users mind because it forces the user to remember this sneaky rule.

Please consider changing this. I understand not wanting to introduce a non-backwards compatible change, but perhaps you can add another param to the function to allow custom options, including a custom env var.

**Comment by ctjlewis** [comment]
I will add an override option.
