### ISSUE TITLE
"Node globals cannot be used in browser"

### ISSUE THREAD

**Issue by Johnrobmiller** [gptlabs/openai-streams#4]
The call stack traces to this library.
Error occured when running `yarn dev` and opening up `localhost:3000`
node version: 18
OS: macOS M1 chip
framework: NextJS (should be obvious but mentioning just in case)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/55205360/219990021-15a9a588-e75d-4e99-b2ac-9d6aefad97b7.png">

**Comment by Johnrobmiller** [comment]
Whoops! Actually, it points to the openai-streams library

**Comment by Johnrobmiller** [comment]
omg 🤣 I thought I was in the nextjs-openai repo when I closed this, but I wasn't. Oh well, I made a duplicate issue

**Comment by ctjlewis** [comment]
lmao no worries, we'll talk on the other thread
