### ISSUE TITLE
"Node globals cannot be used in browser"

### ISSUE THREAD

**Issue by Johnrobmiller** [gptlabs/openai-streams#5]
The call stack traces to this library.
Error occured when running yarn dev and opening up localhost:3000
node version: 18
OS: macOS M1 chip
framework: NextJS (should be obvious but mentioning just in case)

![image](https://user-images.githubusercontent.com/55205360/219990512-6427dac9-447e-4d8a-a4d2-1559b9cb42f3.png)

**Comment by ctjlewis** [comment]
Hey, are you trying to use `await OpenAI()` on the client?

This would leak your API key into the client bundle, this is an older version of the library freaking out and disallowing it.

If you're just using it in `getServerSideProps()` or something, upgrading *should* get rid of this but if it didn't you could `await import("...")` inside `getServerSideProps()` to make sure it doesn't end up in the client.

**Comment by Johnrobmiller** [comment]
It's only being imported in one place, and that's in the `triniti` api route. SS: 
<img width="936" alt="image" src="https://user-images.githubusercontent.com/55205360/219993059-c8487aa3-c69c-4536-adb7-f5f1a6bf0431.png">

**Comment by Johnrobmiller** [comment]
I found the problem

`./node_modules/nextjs-openai/node_modules/openai-streams/dist/globs/node.js`

This is in the `nextjs-openai` module, not this one. However, there `openai-streams` is installed within the `nextjs-openai` module, and because I'm using `nextjs-openai` on the client, this might be the reason it's throwing this error

**Comment by ctjlewis** [comment]
Ah, yes. I stupidly re-exported the server-side only library at the client-side entry-point. Very true John, that is absolutely the problem, my bad. Let me try to fix it.

Thanks for being patient through these issues.

**Comment by ctjlewis** [comment]
The confusing thing is these globals aren't used on latest anymore anyway, I'm trying to figure out how it's getting in the path, but your debug info is super helpful.

I figured it would be easier keeping these two libs separate than rolling them into one huge one but that's not looking as easy as I thought. Trying to fix this rn.

**Comment by ctjlewis** [comment]
Also the Next.js library is itself a demo and doesn't repro, trying to figure out why.

**Comment by ctjlewis** [comment]
So sorry for that again @Johnrobmiller. This should be fixed on latest. Docs should be up to date as well.

```bash
yarn add nextjs-openai openai-streams

# -or-

npm i --save nextjs-openai openai-streams
```
